pptp:
  image: vimagick/pptp
  environment:
    - SERVER=192.168.31.222
    - TUNNEL=vps
    - USERNAME=username
    - PASSWORD=password
    - ROUTES=0.0.0.0/1 128.0.0.0/1
  net: host
  privileged: yes
  restart: unless-stopped
